### ISSUE TITLE
Please help me solve the problem

### ISSUE THREAD

**Issue by Frewnd** [BojarLab/FragmentFactory#1]
I run the instruction as follows:
       python train.py FragmentFactory_dataset.pkl output（The default weighting was modified as True in train.py by me）

Then, there is error:
       Traceback (most recent call last):
           File "E:\Data\WorkSpace\Git\oglycan\FragmentFactory\train.py", line 275, in <module>
                spec2svg(args.in_filename, args.output_path_prefix, weighting=args.weighting, GPID_SIM=args.GPID_SIM)
           File "E:\Data\WorkSpace\Git\oglycan\FragmentFactory\train.py", line 231, in spec2svg
                data, tree = train_topo_tree(in_filename, weighting=weighting, GPID_SIM=GPID_SIM)
           File "E:\Data\WorkSpace\Git\oglycan\FragmentFactory\train.py", line 215, in train_topo_tree
                data = TopoData(spec_df, weighting=weighting, GPID_SIM=GPID_SIM)
           File "E:\Data\WorkSpace\Git\oglycan\FragmentFactory\train.py", line 84, in __init__
                self.df = split(spec_df, GPID_SIM=GPID_SIM)
           File "E:\Data\WorkSpace\Git\oglycan\FragmentFactory\train.py", line 21, in split
                "X": list(np.stack(spec_df["binned_intensities_norm"].values)),
           File "E:\Data\Backup\Config\Anaconda\envs\ff\lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
                indexer = self.columns.get_loc(key)
           File "E:\Data\Backup\Config\Anaconda\envs\ff\lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
                raise KeyError(key) from err
           KeyError: 'binned_intensities_norm'

I attempt to resolve this error, yet whatever approach I take proves ineffective. Would you like to give me a hand?

**Comment by Old-Shatterhand** [comment]
Hi @Frewnd,

Sorry for the delayed answer. Could you share the file you're using as input?

The code requires the pandas DataFrame (your CSV file) to have the following columns (additional columns will be ignored/are not relevant to the model):

- `binned_intensities_norm`: These are the intensities from the MS/MS spectra binned in ranges and normalized to sum to 1.
- `glycan`: The IUPAC-condensed string of the glycans
- `filename`: The DOI of the publication where the spectra were published
- `GP_ID`: The GlycoPost_ID of glycans

The last two columns were used to reduce information leakage between splits and can be left empty to get a random split.

**Comment by Frewnd** [comment]
> Hi @Frewnd,
> 
> Sorry for the delayed answer. Could you share the file you're using as input?
> 
> The code requires the pandas DataFrame (your CSV file) to have the following columns (additional columns will be ignored/are not relevant to the model):
> 
> * `binned_intensities_norm`: These are the intensities from the MS/MS spectra binned in ranges and normalized to sum to 1.
> * `glycan`: The IUPAC-condensed string of the glycans
> * `filename`: The DOI of the publication where the spectra were published
> * `GP_ID`: The GlycoPost_ID of glycans
> 
> The last two columns were used to reduce information leakage between splits and can be left empty to get a random split.

I'm really happy to see your reply! I've been a bit busy lately and forgot to follow up, so I apologize for the delayed response. My dataset was downloaded from the URL provided in the paper: https://zenodo.org/records/12177171. The file I downloaded is 'FragmentFactory_dataset.pkl'. Could it be that I missed some steps in the process? Thank you for your help!

**Comment by Old-Shatterhand** [comment]
Hi @Frewnd,

could you share a script of what you're doing?

Best, Roman

**Comment by Old-Shatterhand** [comment]
Ok, I checked the pickle file and found the issue. The dataframe has been pickled and uploaded without the `binned_intensities_norm` field. The reason was that one might want to use a different binning than we did, but to use the Zenodo-File as an example the intensities should be included. We'll work on it and let you know when it's fixed.

@urbj could you please upload the data frame with the intensities and add a script/description to the readme on how you calculate the binned_intensities from the dict in the `peak_d` column.

**Comment by Frewnd** [comment]
> Ok, I checked the pickle file and found the issue. The dataframe has been pickled and uploaded without the `binned_intensities_norm` field. The reason was that one might want to use a different binning than we did, but to use the Zenodo-File as an example the intensities should be included. We'll work on it and let you know when it's fixed.
> 
> @urbj could you please upload the data frame with the intensities and add a script/description to the readme on how you calculate the binned_intensities from the dict in the `peak_d` column.

Thank you very much, and I look forward to your reply! （PS: I am a graduate student specializing in O-glycans, and I am very interested in the machine learning methods used in this paper. I would like to reproduce the results first to see how they turn out. I am using all the code and datasets mentioned in the paper, which is titled: "Navigating the maze of mass spectra: a machine-learning guide to identifying diagnostic ions in O-glycan analysis."）

**Comment by urbj** [comment]
Hi @Frewnd!

I have uploaded a preprocessing script and changed the README in efa6fafb455d9a28701ebd2085ad8a1de8fa4949. You should be able to run the script and then specify the new processed file as an argument like so:
``` bash
train.py ./FragmentFactory_dataset_processed.pkl <output-prefix> --weighting --GPID_SIM <val>

```

Let me know if this fixes the issue for you~~

**Comment by Frewnd** [comment]
> Hi [@Frewnd](https://github.com/Frewnd)!
> 
> I have uploaded a preprocessing script and changed the README in [efa6faf](https://github.com/BojarLab/FragmentFactory/commit/efa6fafb455d9a28701ebd2085ad8a1de8fa4949). You should be able to run the script and then specify the new processed file as an argument like so:
> 
> train.py ./FragmentFactory_dataset_processed.pkl <output-prefix> --weighting --GPID_SIM <val>
> Let me know if this fixes the issue for you~~
I ran the **FF_data_preprocessing.py** and obtained **FragmentFactory_dataset_processed.pkl**.Then, I entered the following command in the terminal:
`python train.py FragmentFactory_dataset_processed.pkl output --weighting --GPID-SIM 0.8`
The following error occurred:
```
Traceback (most recent call last):
  File "E:\Data\WorkSpace\PyCharm\PaperDemo\oglycan\FragmentFactory\train.py", line 275, in <module>
    spec2svg(args.in_filename, args.output_path_prefix, weighting=args.weighting, GPID_SIM=args.GPID_SIM)
  File "E:\Data\WorkSpace\PyCharm\PaperDemo\oglycan\FragmentFactory\train.py", line 231, in spec2svg
    data, tree = train_topo_tree(in_filename, weighting=weighting, GPID_SIM=GPID_SIM)
  File "E:\Data\WorkSpace\PyCharm\PaperDemo\oglycan\FragmentFactory\train.py", line 215, in train_topo_tree
    data = TopoData(spec_df, weighting=weighting, GPID_SIM=GPID_SIM)
  File "E:\Data\WorkSpace\PyCharm\PaperDemo\oglycan\FragmentFactory\train.py", line 84, in __init__
    self.df = split(spec_df, GPID_SIM=GPID_SIM)
  File "E:\Data\WorkSpace\PyCharm\PaperDemo\oglycan\FragmentFactory\train.py", line 21, in split
    "X": list(np.stack(spec_df["binned_intensities_norm"].values)),
  File "<__array_function__ internals>", line 180, in stack
  File "E:\Data\Backup\Config\Anaconda\envs\ff\lib\site-packages\numpy\core\shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

**Comment by urbj** [comment]
Hi @Frewnd!

I have amended the preprocessing script to output a fixed bin number such that the arrays can be stacked here 83a3dbb75eef472d8f08fa23ed270da3d5cc569b. 

This should resolve the problem~
